### PR TITLE
Yo I added a PoggersDB

### LINKED ISSUE #4: Needs more poggers
Add a .poggers extension 👀

### PR DESCRIPTION
**Pull request by Grazen0**
That's really poggers

### CODE REVIEW

**Review by alexanderpaolini — CHANGES_REQUESTED** [review]
Change indentation to 2 spaces, and format with standard, change errors to be the same as I use.

**Comment by alexanderpaolini** [comment]
alright time to push

**Comment by alexanderpaolini** [comment]
merge*

**Comment by Grazen0** [comment]
poggers

**Pull request merged**
