### PR TITLE
Formatted code and added comments

### PR DESCRIPTION
**Pull request by Grazen0**
Bruh I forgot to make another branch

### CODE REVIEW

**Review by apaolini1321 — APPROVED** [review]
looks good, I will be changing indentation though

**Comment by AlexanderPaolini** [comment]
damn it wrong account

**Comment by alexanderpaolini** [comment]
no MILLION you can't just pick a random change and hit resolved

**Comment by alexanderpaolini** [comment]
changes go brrrrrrrrr

**Pull request merged**
